logging:
    level:
        org:
            zalando:
                logbook: TRACE
        ru:
            yandex:
                practicum:
                    contollers: debug
server:
    error:
        include-message: always
