logging:
    level:
        org:
            zalando:
                logbook: TRACE
        ru:
            yandex:
                practicum:
                    contollers: debug
server:
    error:
        include-message: always
    servlet:
        encoding:
            charset: UTF-8
            charset.force-response: true
            charset.force-request: true

spring:
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:h2:./db/filmorate;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
        driver-class-name: org.h2.Driver
        username: sa
        password: password
