logging:
    level:
        org:
            zalando:
                logbook: TRACE
        ru:
            yandex:
                practicum:
                    contollers: debug
server:
    error:
        include-message: always
    servlet:
        encoding:
            charset: UTF-8
            charset.force-response: true
            charset.force-request: true
