CREATE TABLE IF NOT EXISTS "FILMS" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        "name" VARCHAR(255) NOT NULL,
                        "release_date" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                        "description" VARCHAR(255) NOT NULL,
                        "duration" INTEGER NOT NULL,
                        "mpa" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "MPA"(
                      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "USERS"(
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "email" VARCHAR(255) NOT NULL,
                        "login" VARCHAR(255) NOT NULL,
                        "name" VARCHAR(255) NOT NULL,
                        "birthday" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS "FRIENDSHIP"(
                             "user_id" BIGINT NOT NULL,
                             "friend_id" BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS "LIKES"(
                        "film_id" BIGINT NOT NULL,
                        "user_id" BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS "FILM_GENRE"(
                             "film_id" BIGINT NOT NULL,
                             "genre_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "GENRES"(
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" VARCHAR(255) NOT NULL
);

ALTER TABLE
    "FRIENDSHIP" ADD CONSTRAINT "friendship_friend_id_foreign" FOREIGN KEY("friend_id") REFERENCES "USERS"("id");
ALTER TABLE
    "FRIENDSHIP" ADD CONSTRAINT "friendship_user_id_foreign" FOREIGN KEY("user_id") REFERENCES "USERS"("id");
ALTER TABLE
    "FILMS" ADD CONSTRAINT "films_mpa_foreign" FOREIGN KEY("mpa") REFERENCES "MPA"("id");
ALTER TABLE
    "LIKES" ADD CONSTRAINT "likes_film_id_foreign" FOREIGN KEY("film_id") REFERENCES "FILMS"("id");
ALTER TABLE
    "LIKES" ADD CONSTRAINT "likes_user_id_foreign" FOREIGN KEY("user_id") REFERENCES "USERS"("id");
ALTER TABLE
    "FILM_GENRE" ADD CONSTRAINT "film_genre_film_id_foreign" FOREIGN KEY("film_id") REFERENCES "FILMS"("id");
ALTER TABLE
    "FILM_GENRE" ADD CONSTRAINT "film_genre_genre_id_foreign" FOREIGN KEY("genre_id") REFERENCES "GENRES"("id");